# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Single sample GSEA
#' 
#' This function returns a List basically a list with the
#' following elements:
#' @return \item{ES}{Enrichiment Score of the pathway w.r.t to gene}
#' @return \item{NES}{Normailized Enrinchment Score}
#' @return \item{p.value}{P value of the estimate}
#' @references 
ssgsea <- function(ref, gs, np = 100L) {
    .Call('_TR2PATH_ssgsea', PACKAGE = 'TR2PATH', ref, gs, np)
}

